### ISSUE TITLE
attempt to index field 'hl_map' (a nil value)

### ISSUE THREAD

**Issue by abdellatif-temsamani** [uga-rosa/sticky-header.nvim#2]
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ...pack/packer/start/sticky-header.nvim/lua/sticky/init.lua:59: attempt to index field 'hl_map' (a nil value)
stack traceback:
        ...pack/packer/start/sticky-header.nvim/lua/sticky/init.lua:59: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:192: in function 'for_each_tree'
        ...pack/packer/start/sticky-header.nvim/lua/sticky/init.lua:50: in function 'get_treesitter_syntax_groups'
        ...pack/packer/start/sticky-header.nvim/lua/sticky/init.lua:16: in function 'run'
        [string ":lua"]:1: in main chunk

**Comment by uga-rosa** [comment]
https://github.com/nvim-treesitter/nvim-treesitter-context
I noticed this after making this plugin, but there is already a similar one.
I'll add a link to the above to the readme and then deprecate it.
